spring:
  application:
    name: Authorization
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_user_security
    username: lukasz
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false

